{{-- ملف Blade للـ PDF - resources/views/tenders/pdf.blade.php --}}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Tenders Report</title>
    
    
    <link rel="stylesheet" href="{{ public_path('/css/pdf.css') }}">
    
   
    <!-- {{-- <link rel="stylesheet" href="{{ asset('/css/pdf.css') }}"> --}} -->
</head>

<body>
    <div class="header">
        <h1>Tenders Report</h1>
        <p>Generated on: {{ now()->format('d M, Y H:i') }}</p>
        <p>Total Tenders: {{ $tenders->count() }}</p>
    </div>

    <table class="no-break">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Number</th>
                <th>Client Type</th>
                <th>Client</th>
                <th>Assigned</th>
                <th>Purchase</th>
                <th>Submit</th>
                <th>Reviewed</th>
                <th>BA Date</th>
                <th>Review Date</th>
                <th>3rd Party</th>
                <th>Follow-up</th>
                <th>Channel</th>
                <th>Notes</th>
                <th>Status</th>
                <th>Cancel Reason</th>
            </tr>
        </thead>
        <tbody>
            @forelse($tenders as $tender)
            <tr class="no-break">
                <td style="text-align: center;">{{ $tender->id }}</td>
                <td class="truncate">{{ $tender->name ?? '-' }}</td>
                <td>{{ $tender->number ?? '-' }}</td>
                <td>{{ $tender->client_type ?? '-' }}</td>
                <td class="truncate">{{ $tender->client_name ?? '-' }}</td>
                <td>{{ $tender->assigned_to ?? '-' }}</td>
                <td>{{ $tender->date_of_purchase ? $tender->date_of_purchase->format('m/d/y') : '-' }}</td>
                <td>{{ $tender->date_of_submission ? $tender->date_of_submission->format('m/d/y') : '-' }}</td>
                <td>{{ $tender->reviewed_by ?? '-' }}</td>
                <td>{{ $tender->date_of_submission_ba ? $tender->date_of_submission_ba->format('m/d/y') : '-' }}</td>
                <td>{{ $tender->date_of_submission_after_review ? $tender->date_of_submission_after_review->format('m/d/y') : '-' }}</td>
                <td style="text-align: center;">{{ $tender->has_third_party ? 'Y' : 'N' }}</td>
                <td>{{ $tender->last_follow_up_date ? $tender->last_follow_up_date->format('m/d/y') : '-' }}</td>
                <td>{{ $tender->follow_up_channel ?? '-' }}</td>
                <td class="truncate">{{ $tender->follow_up_notes ?? '-' }}</td>
                <td class="
                    @if($tender->status == 'Active') status-active
                    @elseif($tender->status == 'Cancelled') status-cancelled  
                    @elseif($tender->status == 'Pending') status-pending
                    @endif
                ">{{ $tender->status ?? '-' }}</td>
                <td class="truncate">{{ $tender->reason_of_cancel ?? '-' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="17" style="text-align: center; padding: 20px; font-size: 12px;">
                    No tenders found
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

   
    <div style="margin-top: 20px; font-size: 8px; text-align: center; color: #666;">
        <p>Report generated by {{ config('app.name') }} | Page 1 of 1</p>
    </div>

</body>
</html>